# Generated by Django 4.2.2 on 2023-07-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project3", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="аватары"
            ),
        ),
    ]
